---
- hosts: ws
  become: true
  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start Daemon
      service:
        name: httpd
        state: started
        enabled: true
    # - name: Delete file if exist
    #   file:
    #     path: /var/www/html/index.html
    #     state: absent
    #   ignore_errors: true
    - name: Create a File
      file:
        dest: /var/www/html/index.html
        state: touch
    - name: Add a line to a file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> This apache is ansible server. </h1>
      notify: Restart Daemon

  handlers:
    - name: Restart Daemon
      service:
        name: httpd
        state: restarted
