---
- hosts: ws
  become: true
  ignore_errors: yes
  gather_facts: yes
  vars:
    package_name: httpd
  tasks:
      - name: Install package
        yum: 
          name: "{{ package_name }}"
          state: present
      # - name: create groups
      #   group:
      #     state: present
      #     name: "{{ item}}"
      #   loop:
      #       - cloud
      #       - security
      #       - linux
      - name: Create group
        group:
          name: "{{ items}}"
          state: present
        with_items:
           - cloud
           - security
           - linuxsa
           - devops