---
- hosts: ws
  become: true
  ignore_errors: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Download file from a file path
      get_url:
         url: "{{ LINK_URL }}"
         dest: "{{ DESTINATION }}"
    - name: Remove directory
      file:
        path: "{{ DESTINATION }}"
        state: absent     
 
        
   